/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poi.excel;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.File;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testExcet() {
        File file = new File("test.xlsx");

        System.out.println(file.length());
    }
}
